# Generated by Django 2.2.5 on 2019-09-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=100)),
                ('pdescription', models.TextField()),
                ('ptechnology', models.CharField(max_length=20)),
                ('pimage', models.FilePathField(path='/img')),
            ],
        ),
    ]
